vpc:
  name: transendence

cluster:
  name: transendence-cluster

roles:
  ecs_task_role_arn: arn:aws:iam::577638398727:role/tmp-transendence-ecs-task-role

services:
  - name: backend
    repo: backend
    port: 3000
    secrets:
      JWT_SECRET: JWT_SECRET
      JWT_EXPIRES_IN: JWT_EXPIRES_IN
      DEFAULT_AVATAR: DEFAULT_AVATAR

  - name: frontend
    repo: frontend
    port: 80
