vpc:
  name: transendence

security_groups:
  - name: lambda-sg
    description: SG for Lambda Functions
    allow_all_outbound: true
    ingress: []

  - name: bastion-sg
    description: SG for Bastion Host
    allow_all_outbound: true
    ingress:
      - protocol: tcp
        port: 22
        source: "0.0.0.0/0"
        description: SSH Access

  - name: ecs-sg
    description: SG for ECS
    allow_all_outbound: true
    ingress: []

  - name: db-sg
    description: SG for RDS
    allow_all_outbound: true
    ingress:
      - protocol: tcp
        port: 5432
        source_sg: ecs-sg
        description: PostgreSQL from ECS
