vpcs:
  - name: transendence
    description: Transendence VPC
    cidr: "10.0.0.0/16"
    subnets:
      - name: Public
        type: PUBLIC
        cidr_mask: 24
      - name: Private
        type: PRIVATE_ISOLATED
        cidr_mask: 24
    nat_gateways: 1
    restrict_default_security_group: False
